### ISSUE TITLE
Pypy compilation broken

### ISSUE THREAD

**Issue by madig** [fonttools/openstep-plist#12]
https://github.com/fonttools/openstep-plist/pull/11/checks?check_run_id=3223222589#step:5:1618

```
   ____________________ ERROR collecting tests/test_parser.py _____________________
  /project/tests/test_parser.py:6: in <module>
      from openstep_plist._test import (
  /tmp/tmp.DzCeH7rRjP/venv/site-packages/openstep_plist/__init__.py:1: in <module>
      from .parser import load, loads, ParseError
  src/openstep_plist/parser.pyx:1: in init openstep_plist.parser
      ???
  E   ValueError: array.array size changed, may indicate binary incompatibility. Expected 72 from C header, got 24 from PyObject
```

**Comment by madig** [comment]
Cosimo says:

> looks like array.array cython bindings rely on cpython internals
> so no pypy for the time being
> https://github.com/cython/cython/issues/3448
> (or we need to not use array.array)

**Comment by anthrotype** [comment]
instead of cpython's `array.array` module (whose C API doesn't work on pypy), maybe we can try to see if we can use the so-called "cython arrays" (i.e. `from cython cimport view; a = view.array(...)`) https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html#cython-arrays

They are similar to numpy arrays, continguous block of memory with similar interface as memoryviews.

**Comment by behdad** [comment]
Or just use `list` and `tuple`. My testing shows that with Python 3.7, 3.8, 3.9 etc list,tuple are significantly faster than even array.array...

**Comment by anthrotype** [comment]
i need something mutable and that can be dynamically extended (we use an array of unicode characters to accummulate the parsed chunks of strings and at the end convert it to a str), so I guess I'll try with a list.
Or we could even use c++ strings or vectors. I'll experiment and see what I come up with.

**Comment by behdad** [comment]
> Or we could even use c++ strings or vectors

Yeah do that then.

I'm looking at this code now. I don't understand a single byte :)).

**Comment by anthrotype** [comment]
I more or less translated almost verbatim the original apple C code to the cython equivalent
