### ISSUE TITLE
no universal2 wheels for ARM64-based M1 macs on PyPI

### ISSUE THREAD

**Issue by anthrotype** [fonttools/openstep-plist#16]
installing openstep-plist on a M1 mac requires building from source, which fails if one doesn't have the compiler toolchain set up.
We need to publish precompiled wheels like we do for the rest of the modules in our font build pipeline. Usually it's as easy as updating cibuildwheel

**Comment by justvanrossum** [comment]
What is currently the workaround? Downgrade to Python 3.9? Use an intel-based Python?

**Comment by justvanrossum** [comment]
The workaround is to use "python3.10-intel64" instead of "python3.10" when setting up the venv :)

**Comment by anthrotype** [comment]
I think xcode-select --install should install the command line tools and allow pip to build for arm64 from source distribution. I'll make wheels when I get back next week
