### ISSUE TITLE
[writer] add option to not escape newline characters

### ISSUE THREAD

**Issue by anthrotype** [fonttools/openstep-plist#23]
as @arrowtype noted in
https://github.com/googlefonts/glyphsLib/issues/953#issuecomment-1789998384

**Comment by arrowtype** [comment]
Amazing, thanks for working on this so fast!

Would I call this like so, or should I adjust my approach?

```py
openstep_plist.dump(data, fontinfo, unicode_escape=False, indent=0, single_line_tuples=False)
```

I’ve pip installed the branch and tested the above, but it still seems to flatten the feature code. Of course, I might be trying it to early, or approaching it in the wrong way.

**Comment by anthrotype** [comment]
you want to also pass the new escape_newlines=False (it is still True by default for backward compat)

**Comment by anthrotype** [comment]
you know it's unlikely we will ever match Glyphs.app output 100% because I know its own writer does things based on knowledge of the kind of attribute it is writing out whereas this is just a general-purpose format agnostic ascii plist parser/writer...

**Comment by arrowtype** [comment]
> you want to also pass the new escape_newlines=False (it is still True by default for backward compat)

Oh, yes! This made things much better. The feature code in fontinfo.plis now appears to be untouched when updating the file externally.

> it's unlikely we will ever match Glyphs.app output 100% because I know its own writer does things based on knowledge of the kind of attribute it is writing out whereas this is just a general-purpose format agnostic ascii plist parser/writer...

This is understandable. Getting this much closer is definitely still a win, though! 

With that in mind, I am curious whether one more thing is possible...

Whether or not I set `single_line_tuples` to `True` or `False`, the guideline positions get expanded when editing with openstep-plist. Is this avoidable, or not really?

<img width="1933" alt="image" src="https://github.com/fonttools/openstep-plist/assets/45946693/c082a6de-e432-4ee3-924d-6bb36d9382bc">

**Comment by anthrotype** [comment]
> Whether or not I set single_line_tuples to True or False, the guideline positions get expanded when editing with openstep-plist.

hm. they probably are not tuples tuples, but lists maybe? I don't know. Off to lunch

**Comment by arrowtype** [comment]
Okay, well thanks again for adding this feature!

**Comment by anthrotype** [comment]
ok I see what's going on.
The openstep_plist parser will parse any plist array into a python `list`. So if you then dump that as a list, the `single_line_tuples=True` option will not have effect on it, for it only applies to `tuples` proper...

If you know what exactly you want to be in a single line you could go through it and convert the lists to tuples before dumping them with `single_line_tuples=True`...

**Comment by arrowtype** [comment]
Ohh interesting. Thanks for the idea! I'll give it a try. For now, I ended up solving my immediate issue with some regex, which seems to work well enough in this case.
