### ISSUE TITLE
Support Glyphs-style "tuples"

### ISSUE THREAD

**Issue by simoncozens** [fonttools/openstep-plist#6]
Glyphs 3 plist files have "tuples" which appear on a single line even when other lines are separated/indented. The easiest way to support this would be to remove the `if indent is not None...` blocks from `write_array_from_tuple`. However, this may have Unintended Consequences.

**Comment by anthrotype** [comment]
ugh. I really wish we can avoid adding quirks to this project, I'd like to keep it general purpose and not tied to Glyphs.app, even if it's the main target. Can we think about ways to inject some custom callbacks to format these maybe?

**Comment by anthrotype** [comment]
on second thought, I guess it'd be fine if we add a new writer option, e.g. `single_line_tuples=False`, that optionally enable this. I see we already have two duplicate implementations for serializing list and tuple objects. Could you send a PR?
